sudo: required

language: minimal

services: docker

install:
    - docker-compose up -d

script:
    - [[ "$(curl -sS -H 'Host: unstable--dummy-api.libero.pub' http://localhost:8080/ping 2>&1)" == "pong" ]]

if: |
    branch = master OR \
    type = pull_request
