language: minimal

dist: bionic

services: docker

install:
    - ln -s .env.dist .env
    - travis_retry docker-compose pull

before_script:
    - .docker/initialize-volumes.sh
    - docker-compose up -d

script:
    - bash -xc "shellcheck -x .docker/*.sh"
    - .travis/smoke-test.sh && .docker/populate-services.sh

deploy:
    provider: script
    script: .scripts/travis/downstream.sh environments "Update sample-configuration to $TRAVIS_COMMIT"
    on:
        branch: master

if: |
    branch = master OR \
    type = pull_request
