sudo: required

language: minimal

env:
    global:
        - COMPOSE_PROJECT_NAME: sampleconfiguration

services: docker

install:
    - ln -s .env.dist .env
    - travis_retry docker-compose pull

before_script:
    - docker-compose up -d

script:
    - .travis/smoke-test.sh

if: |
    branch = master OR \
    type = pull_request
