sudo: required

language: minimal

services: docker

install:
    - travis_retry docker-compose pull
    - ln -s .env.dist .env

before_script:
    - docker-compose up -d

script:
    - .travis/smoke

if: |
    branch = master OR \
    type = pull_request
