version: '3.6'

services:
    elife-style-content-adapter:
        secrets:
            # mounted at /run/secrets/elife-style-content-adapter-aws-credentials
            - elife-style-content-adapter-aws-credentials

secrets:
    elife-style-content-adapter-aws-credentials:
        file: ./secrets/elife-style-content-adapter-aws-credentials.secret
