version: '3.4'

services:
    blog-articles_fpm:
        command: >
            sh -c '
                mkdir -p ~/.aws
                ln -sf /run/secrets/blog-articles-aws-credentials ~/.aws/credentials
                while ! nc blog-articles_postgres 5432; do sleep 1; done
                bin/console doctrine:migrations:migrate --no-interaction
                php-fpm
            '
        environment:
            S3_BUCKET: unstable-blog-articles-assets
            ASSETS_PUBLIC_URI: https://unstable-blog-articles-assets.s3.us-east-1.amazonaws.com
        secrets:
            # mounted at /run/secrets/blog-articles-aws-credentials
            - blog-articles-aws-credentials
    jats-ingester_webserver:
        command: sh -c 'mkdir -p ~/.aws && ln -sf /run/secrets/jats-ingester-aws-credentials ~/.aws/credentials && airflow upgradedb && airflow webserver -p 8080'
        secrets:
            - jats-ingester-aws-credentials
    jats-ingester_scheduler:
        command: sh -c 'mkdir -p ~/.aws && ln -sf /run/secrets/jats-ingester-aws-credentials ~/.aws/credentials && airflow scheduler'
        secrets:
            - jats-ingester-aws-credentials
    jats-ingester_worker:
        command: sh -c 'mkdir -p ~/.aws && ln -sf /run/secrets/jats-ingester-aws-credentials ~/.aws/credentials && airflow worker'
        secrets:
            - jats-ingester-aws-credentials
    scholarly-articles_fpm:
        command: >
            sh -c '
                mkdir -p ~/.aws
                ln -sf /run/secrets/scholarly-articles-aws-credentials ~/.aws/credentials
                while ! nc scholarly-articles_postgres 5432; do sleep 1; done
                bin/console doctrine:migrations:migrate --no-interaction
                php-fpm
            '
        environment:
            S3_BUCKET: unstable-scholarly-articles-assets
            ASSETS_PUBLIC_URI: https://unstable-scholarly-articles-assets.s3.us-east-1.amazonaws.com
        secrets:
            # mounted at /run/secrets/scholarly-articles-aws-credentials
            - scholarly-articles-aws-credentials

secrets:
    blog-articles-aws-credentials:
        file: ./secrets/blog-articles-aws-credentials.secret
    elife-style-content-adapter-aws-credentials:
        file: ./secrets/elife-style-content-adapter-aws-credentials.secret
    jats-ingester-aws-credentials:
        file: ./secrets/jats-ingester-aws-credentials.secret
    scholarly-articles-aws-credentials:
        file: ./secrets/scholarly-articles-aws-credentials.secret
